const consoleData = [
  // First generation
  {
    generation: 1,
    name: "Magnavox Odyssey",
    releaseYear: 1972,
    originalPrice: 100,
    inflationAdjustedPrice: 553,
    globalSales: 350000,
    manufacturer: "Magnavox",
    cpu: "None (Analog circuits)",
    memory: "None",
    resolution: "None (Overlays on TV)",
    colors: "Black and white",
    mediaFormat: "Built-in games with plastic overlays",
    description:
      "The world's first commercial home video game console. Instead of using digital logic, it used analog circuitry and television screen overlays to simulate various games.",
    notableGames: ["Table Tennis", "Ski", "Simon Says", "Football"],
    funFacts: [
      "Used plastic overlays on the TV screen to add color and graphics",
      "Designed by Ralph Baer, 'The Father of Video Games'",
      "Had no sound capability",
      "Powered by batteries",
    ],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Magnavox-Odyssey-2-Console-Set.png/1024px-Magnavox-Odyssey-2-Console-Set.png",
  },

  // Second generation
  {
    generation: 2,
    name: "Atari 2600",
    releaseYear: 1977,
    originalPrice: 200,
    inflationAdjustedPrice: 882,
    globalSales: 30000000,
    manufacturer: "Atari, Inc.",
    cpu: "MOS Technology 6507 @ 1.19 MHz",
    memory: "128 bytes RAM",
    resolution: "160 × 192 pixels",
    colors: "128 colors (NTSC)",
    mediaFormat: "ROM cartridge",
    description:
      "Originally sold as the Atari Video Computer System (VCS), the 2600 helped establish the home video game industry through the late 1970s and early 1980s. It became so successful that 'Atari' was a synonym for the system in mainstream media.",
    notableGames: [
      "Space Invaders",
      "Pitfall!",
      "Adventure",
      "Pac-Man",
      "Combat",
    ],
    funFacts: [
      "The E.T. game for the Atari 2600 is often cited as contributing to the video game crash of 1983",
      "Had distinctive woodgrain paneling on early models",
      "Joystick became iconic in gaming culture",
      "Remained in production until 1992 - an impressive 15-year lifespan",
    ],
    imageUrl:
      "https://pub-2e8272d5c74b4466a558e2a7dedb63cf.r2.dev/Atari-2600-Tele-Games-FL.png",
  },
  {
    generation: 2,
    name: "Intellivision",
    releaseYear: 1979,
    originalPrice: 300,
    inflationAdjustedPrice: 996,
    globalSales: 3000000,
    manufacturer: "Mattel Electronics",
    cpu: "General Instrument CP1610 @ 1 MHz",
    memory: "1452 bytes RAM",
    resolution: "160 × 196 pixels",
    colors: "16 colors",
    mediaFormat: "ROM cartridge",
    description:
      "The Intellivision was the first 16-bit gaming console and Mattel's response to the Atari 2600. It was known for better graphics and more sophisticated gameplay than its competitors at the time.",
    notableGames: [
      "Astrosmash",
      "Major League Baseball",
      "Advanced Dungeons & Dragons",
      "Burger Time",
    ],
    funFacts: [
      "Featured the first licensed sports video games",
      "Had a unique controller with a 12-button numeric keypad",
      "Mattel planned a keyboard add-on to make it a full computer",
      "Voice synthesis module allowed games to have speech",
    ],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Intellivision-Console-Set.png/800px-Intellivision-Console-Set.png",
  },
  {
    generation: 2,
    name: "Atari 5200",
    releaseYear: 1982,
    originalPrice: 270,
    inflationAdjustedPrice: 740,
    globalSales: 1400000,
    manufacturer: "Atari, Inc.",
    cpu: "MOS Technology 6502C @ 1.79 MHz",
    memory: "16 KB RAM",
    resolution: "320 × 192 pixels",
    colors: "256 colors (16 at once)",
    mediaFormat: "ROM cartridge",
    description:
      "The Atari 5200 SuperSystem was Atari's attempt to replace the aging Atari 2600 and compete with the Intellivision. It was essentially an Atari 8-bit computer repackaged as a game console.",
    notableGames: ["Pac-Man", "Centipede", "Missile Command", "Star Raiders"],
    funFacts: [
      "Controllers had an analog joystick, numeric keypad, and pause button (innovative for its time)",
      "Many controllers suffered from reliability issues with the joystick",
      "Not backwards compatible with Atari 2600 games without an adapter",
      "Had four controller ports built-in, allowing for 4-player games",
    ],
    imageUrl:
      "https://pub-2e8272d5c74b4466a558e2a7dedb63cf.r2.dev/Atari-5200-4-Port-wController-L.png",
  },
  {
    generation: 2,
    name: "Colecovision",
    releaseYear: 1982,
    originalPrice: 175,
    inflationAdjustedPrice: 480,
    globalSales: 2000000,
    manufacturer: "Coleco",
    cpu: "Zilog Z80A @ 3.58 MHz",
    memory: "8 KB RAM",
    resolution: "256 × 192 pixels",
    colors: "16 colors",
    mediaFormat: "ROM cartridge",
    description:
      "The ColecoVision offered arcade-quality graphics and gaming experiences, and the ability to expand the system with add-ons. It was a technological leap ahead of competitors but was caught in the 1983 video game crash.",
    notableGames: ["Donkey Kong", "Zaxxon", "Venture", "Ladybug"],
    funFacts: [
      "Launched with a home version of Nintendo's Donkey Kong",
      "The Expansion Module #1 allowed it to play Atari 2600 games",
      "Had plans for a full computer add-on called ADAM",
      "The controller featured both a joystick and telephone-style keypad",
    ],
    imageUrl:
      "https://pub-2e8272d5c74b4466a558e2a7dedb63cf.r2.dev/ColecoVision-wController-L.png",
  },

  // Third generation
  {
    generation: 3,
    name: "Famicom",
    releaseYear: 1983,
    originalPrice: 100,
    inflationAdjustedPrice: 273,
    globalSales: 19350000,
    manufacturer: "Nintendo",
    cpu: "Ricoh 2A03 (MOS Technology 6502 core) @ 1.79 MHz",
    memory: "2 KB RAM",
    resolution: "256 × 240 pixels",
    colors: "52 colors (24 on screen)",
    mediaFormat: "ROM cartridge",
    description:
      "The Family Computer (Famicom) was the Japanese version of what would later be known as the Nintendo Entertainment System (NES) in North America. Its success in Japan helped revitalize the video game industry after the crash of 1983.",
    notableGames: [
      "Super Mario Bros.",
      "The Legend of Zelda",
      "Dragon Quest",
      "Final Fantasy",
    ],
    funFacts: [
      "Controllers were hardwired to the console",
      "Featured a distinctive red and white color scheme",
      "Had a microphone on the second controller for certain games",
      "Early versions had problems with the circuit board cracking",
    ],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Nintendo-Famicom-Console-Set-FL.png/800px-Nintendo-Famicom-Console-Set-FL.png",
  },
  {
    generation: 3,
    name: "NES",
    releaseYear: 1985,
    originalPrice: 179,
    inflationAdjustedPrice: 422,
    globalSales: 61910000,
    manufacturer: "Nintendo",
    cpu: "Ricoh 2A03 (MOS Technology 6502 core) @ 1.79 MHz",
    memory: "2 KB RAM",
    resolution: "256 × 240 pixels",
    colors: "52 colors (24 on screen)",
    mediaFormat: "ROM cartridge",
    description:
      "The Nintendo Entertainment System (NES) revitalized the video game industry in North America after the video game crash of 1983. Its design was intentionally made to look like a VCR rather than a toy to appeal to a wider audience.",
    notableGames: [
      "Super Mario Bros.",
      "The Legend of Zelda",
      "Metroid",
      "Mega Man 2",
      "Contra",
    ],
    funFacts: [
      "Used a front-loading design unlike its Japanese counterpart",
      "The Zapper light gun accessory allowed for shooting games",
      "Nintendo implemented a security chip to control game publishing",
      "The 'Nintendo Seal of Quality' was introduced to combat poor quality games",
    ],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/NES-Console-Set.png/800px-NES-Console-Set.png",
  },
  {
    generation: 3,
    name: "Atari 7800",
    releaseYear: 1986,
    originalPrice: 140,
    inflationAdjustedPrice: 323,
    globalSales: 3770000,
    manufacturer: "Atari Corporation",
    cpu: "Atari SALLY (6502) @ 1.79 MHz",
    memory: "4 KB RAM",
    resolution: "320 × 200 pixels",
    colors: "256 colors (25 on screen)",
    mediaFormat: "ROM cartridge",
    description:
      "The Atari 7800 ProSystem was designed to be backward compatible with the Atari 2600, and featured significant technical improvements. Despite being ready in 1984, its release was delayed until 1986 due to the sale of Atari's consumer division.",
    notableGames: ["Pole Position II", "Asteroids", "Galaga", "Food Fight"],
    funFacts: [
      "Was almost released in 1984 but shelved during the sale of Atari",
      "Fully backward compatible with nearly all Atari 2600 games",
      "Had an advanced graphics chip called MARIA",
      "Nintendo's licensing practices made it difficult for Atari to secure third-party games",
    ],
    imageUrl:
      "https://pub-2e8272d5c74b4466a558e2a7dedb63cf.r2.dev/Atari-7800-wControl-Pad-L.png",
  },
  {
    generation: 3,
    name: "SG-1000",
    releaseYear: 1983,
    originalPrice: 15000, // Japanese yen
    inflationAdjustedPrice: null, // Placeholder
    globalSales: 1400000,
    manufacturer: "Sega",
    cpu: "Zilog Z80A @ 3.58 MHz",
    memory: "1 KB RAM",
    resolution: "256 × 192 pixels",
    colors: "16 colors",
    mediaFormat: "ROM cartridge, card",
    description:
      "The SG-1000 (Sega Game 1000) was Sega's first entry into the home video game console market. It was released the same day as the Nintendo Famicom in Japan, but was less successful and is mostly notable as Sega's first console.",
    notableGames: ["Congo Bongo", "Champion Boxing", "Girl's Garden", "Flicky"],
    funFacts: [
      "Released on the exact same day as the Famicom in Japan",
      "Had very limited success outside of Japan",
      "Later models could be converted into a personal computer (SC-3000)",
      "Used the same CPU as the ColecoVision",
    ],
    imageUrl:
      "https://pub-2e8272d5c74b4466a558e2a7dedb63cf.r2.dev/960px-Sega-SG-1000-Console-Set.png",
  },
  {
    generation: 3,
    name: "Master System",
    releaseYear: 1986,
    originalPrice: 200,
    inflationAdjustedPrice: 461,
    globalSales: 13000000,
    manufacturer: "Sega",
    cpu: "Zilog Z80A @ 4 MHz",
    memory: "8 KB RAM",
    resolution: "256 × 192 pixels",
    colors: "64 colors (32 on screen)",
    mediaFormat: "ROM cartridge, card",
    description:
      "The Sega Master System was the successor to the SG-1000 and competed with the NES. While it struggled in Japan and North America, it found great success in Europe and Brazil, where it continued to sell well into the 1990s.",
    notableGames: [
      "Phantasy Star",
      "Alex Kidd in Miracle World",
      "Wonder Boy III: The Dragon's Trap",
      "Sonic the Hedgehog",
    ],
    funFacts: [
      "Had a built-in game (usually Alex Kidd or Hang-On) in later models",
      "Featured 3D glasses as an accessory for special games",
      "Outsold the NES in Europe and Brazil",
      "Still being produced in Brazil until 2018 - over 30 years after its initial release",
    ],
    imageUrl:
      "https://pub-2e8272d5c74b4466a558e2a7dedb63cf.r2.dev/Sega-Master-System-Set.png",
  },
  {
    generation: 3,
    name: "Game Boy",
    releaseYear: 1989,
    originalPrice: 90,
    inflationAdjustedPrice: 184,
    globalSales: 118690000,
    manufacturer: "Nintendo",
    cpu: "Sharp LR35902 (hybrid 8080/Z80) @ 4.19 MHz",
    memory: "8 KB RAM",
    resolution: "160 × 144 pixels",
    colors: "4 shades of green",
    mediaFormat: "ROM cartridge",
    description:
      "The Game Boy was Nintendo's first handheld console and became one of the most iconic gaming devices ever made. Despite its monochrome display and less powerful hardware than competitors, its battery life and game library made it a massive success.",
    notableGames: [
      "Tetris",
      "Pokémon Red/Blue",
      "Super Mario Land",
      "The Legend of Zelda: Link's Awakening",
    ],
    funFacts: [
      "Bundled with Tetris, which helped drive its tremendous popularity",
      "Survived being bombed during the Gulf War and still worked (on display at Nintendo NYC)",
      "Designer Gunpei Yokoi's philosophy was using 'mature technology in a new way'",
      "The entire Game Boy line sold over 200 million units worldwide",
    ],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Game-Boy-FL.png/494px-Game-Boy-FL.png",
  },

  // Fourth generation
  {
    generation: 4,
    name: "TurboGrafx-16",
    releaseYear: 1989,
    originalPrice: 200,
    inflationAdjustedPrice: 408,
    globalSales: 10000000,
    manufacturer: "NEC Home Electronics",
    cpu: "Hudson Soft HuC6280 @ 7.16 MHz",
    memory: "8 KB RAM",
    resolution: "256 × 224 or 512 × 224 pixels",
    colors: "512 colors (482 on screen)",
    mediaFormat: "HuCard, CD-ROM (with attachment)",
    description:
      "Known as the PC Engine in Japan, the TurboGrafx-16 was a 16-bit console that was the first to have a CD-ROM add-on. It was hugely popular in Japan but struggled to gain traction in North America against Nintendo and Sega.",
    notableGames: [
      "Bonk's Adventure",
      "Ys Book I & II",
      "Castlevania: Rondo of Blood",
      "Military Madness",
    ],
    funFacts: [
      "Despite the name, it actually used an 8-bit CPU with a 16-bit graphics chip",
      "The PC Engine was the smallest major console ever made",
      "Its CD-ROM add-on (the first for any console) made it capable of playing Red Book audio",
      "In Japan, it outsold the Mega Drive/Genesis and was second only to the Super Famicom",
    ],
    imageUrl:
      "https://pub-2e8272d5c74b4466a558e2a7dedb63cf.r2.dev/800px-TurboGrafx16-Console-Set.png",
  },
  {
    generation: 4,
    name: "Genesis",
    releaseYear: 1989,
    originalPrice: 190,
    inflationAdjustedPrice: 388,
    globalSales: 30750000,
    manufacturer: "Sega",
    cpu: "Motorola 68000 @ 7.6 MHz",
    memory: "64 KB RAM",
    resolution: "320 × 224 pixels",
    colors: "512 colors (64 on screen)",
    mediaFormat: "ROM cartridge",
    description:
      "Known as the Mega Drive outside North America, the Genesis was Sega's most successful console. Its marketing campaign 'Genesis does what Nintendon't' and the creation of mascot Sonic the Hedgehog helped Sega challenge Nintendo's dominance.",
    notableGames: [
      "Sonic the Hedgehog",
      "Streets of Rage 2",
      "Phantasy Star IV",
      "Gunstar Heroes",
      "Aladdin",
    ],
    funFacts: [
      "Famous for the 'Sega!' chant in TV commercials",
      "Had multiple add-ons including the Sega CD and 32X",
      "Featured a six-button controller revision for fighting games",
      "In Brazil, the Mega Drive was produced until 2017 - almost 30 years after launch",
    ],
    imageUrl:
      "https://pub-2e8272d5c74b4466a558e2a7dedb63cf.r2.dev/Sega-Mega-Drive-JP-Mk1-Console-Set.png",
  },
  {
    generation: 4,
    name: "SNES",
    releaseYear: 1991,
    originalPrice: 200,
    inflationAdjustedPrice: 371,
    globalSales: 49100000,
    manufacturer: "Nintendo",
    cpu: "Ricoh 5A22 (based on 65c816) @ 3.58 MHz",
    memory: "128 KB RAM",
    resolution: "256 × 224 pixels",
    colors: "32,768 colors (256 on screen)",
    mediaFormat: "ROM cartridge",
    description:
      "The Super Nintendo Entertainment System (SNES) was Nintendo's 16-bit console and second home console. It featured enhanced graphics and sound compared to the NES, and is considered by many to have one of the strongest game libraries of any console.",
    notableGames: [
      "Super Mario World",
      "The Legend of Zelda: A Link to the Past",
      "Chrono Trigger",
      "Super Metroid",
      "Final Fantasy VI",
    ],
    funFacts: [
      "North American and European versions had a different design than the Japanese Super Famicom",
      "Mode 7 graphics allowed for pseudo-3D rotation and scaling effects",
      "The PlayStation was originally planned as a CD add-on for the SNES",
      "Cartridges contained special chips (like the SuperFX) to enhance capabilities",
    ],
    imageUrl:
      "https://pub-2e8272d5c74b4466a558e2a7dedb63cf.r2.dev/Wikipedia_SNES_PAL.png",
  },
  {
    generation: 4,
    name: "CD-i",
    releaseYear: 1991,
    originalPrice: 700,
    inflationAdjustedPrice: 1298,
    globalSales: 1000000,
    manufacturer: "Philips",
    cpu: "Philips 68070 @ 15.5 MHz",
    memory: "1 MB RAM",
    resolution: "384 × 280 pixels",
    colors: "16.7 million colors",
    mediaFormat: "CD-ROM",
    description:
      "The Philips CD-i (Compact Disc Interactive) was a multimedia CD player designed for both gaming and educational/reference applications. It's infamous for its poorly received Nintendo-licensed games and is often considered a commercial failure.",
    notableGames: [
      "The Legend of Zelda: Link's Faces of Evil",
      "Hotel Mario",
      "Burn:Cycle",
      "Voyeur",
    ],
    funFacts: [
      "Resulted from a failed deal between Philips and Nintendo to create a CD add-on for the SNES",
      "The Zelda and Mario games are widely considered some of the worst of their franchises",
      "System was marketed more as an educational/multimedia device than a game console",
      "Cost between $700-1000 at launch - extremely expensive for the time",
    ],
    imageUrl:
      "https://pub-2e8272d5c74b4466a558e2a7dedb63cf.r2.dev/CD-i-910-Console-Set.png",
  },
  {
    generation: 4,
    name: "Neo Geo",
    releaseYear: 1991,
    originalPrice: 650,
    inflationAdjustedPrice: 1205,
    globalSales: 980000,
    manufacturer: "SNK",
    cpu: "Motorola 68000 @ 12 MHz + Zilog Z80A @ 4 MHz",
    memory: "64 KB RAM",
    resolution: "320 × 224 pixels",
    colors: "65,536 colors (4,096 on screen)",
    mediaFormat: "ROM cartridge",
    description:
      "The Neo Geo AES (Advanced Entertainment System) was a home version of SNK's arcade system. It was the most powerful console of its era and the first to use memory cards. Its extremely high price made it a luxury item for most gamers.",
    notableGames: [
      "Metal Slug",
      "King of Fighters",
      "Samurai Shodown",
      "Fatal Fury",
    ],
    funFacts: [
      "Cartridges could cost up to $300 each",
      "Identical to the arcade MVS system, allowing perfect arcade ports",
      "Used memory cards before they became standard for saving game progress",
      "Cartridges were massive compared to other systems - some over 700 MB in size",
    ],
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Neo-Geo-AES-Console-Set.png/960px-Neo-Geo-AES-Console-Set.png",
  },
  {
    generation: 4,
    name: "Sega CD",
    releaseYear: 1992,
    originalPrice: 300,
    inflationAdjustedPrice: 540,
    globalSales: 2240000,
    manufacturer: "Sega",
    cpu: "Main: Motorola 68000 @ 12.5 MHz, Sub: Motorola 68000 @ 7.6 MHz",
    memory: "512 KB RAM + 256 KB video RAM",
    resolution: "320 × 224 pixels",
    colors: "512 colors (64 on screen)",
    mediaFormat: "CD-ROM",
    description:
      "The Sega CD (Mega-CD in Europe/Japan) was an add-on for the Sega Genesis that used CD-ROM technology. It offered enhanced audio capabilities, full-motion video, and larger game capacity, but struggled with a high price and many low-quality FMV games.",
    notableGames: [
      "Sonic CD",
      "Snatcher",
      "Lunar: The Silver Star",
      "Night Trap",
      "Final Fight CD",
    ],
    funFacts: [
      "Had two different designs based on which Genesis model it attached to",
      "Featured games with full-motion video, a novelty at the time",
      "Night Trap, one of its games, helped prompt U.S. Congress hearings on video game violence",
      "Had a built-in battery backup for save data",
    ],
    imageUrl:
      "https://pub-2e8272d5c74b4466a558e2a7dedb63cf.r2.dev/Sega-CD-Model2-Set.png",
  },
];
